---
- name: "Test for `go` bin"
  ansible.builtin.command: "command -v go"
  ignore_errors: yes
  register: go_bin_check_output

- name: Installing Global Node packages
  ansible.builtin.command: "go install {{ item }}"
  loop: "{{ packages.go }}"
  when: go_bin_check_output is succeeded
