---
- name: "Test for `npm` bin"
  ansible.builtin.command: "command -v npm"
  ignore_errors: true
  register: npm_bin_check_output

- name: Installing Global Node packages
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop: "{{ packages.npm }}"
  when: npm_bin_check_output is succeeded
