# ------------
# Strings

bins_dir: "{{ ansible_user_dir }}/.bins"
git_path: "{{ ansible_user_dir }}/git"
github_path: "{{ git_path }}/github.com"
dotfiles_path: "{{ github_path }}/reynn/dotfiles"

# ------------
# Secrets
ssh_keys: "{{ vault_ssh_keys }}"
ssh_hosts: "{{ vault_ssh_hosts }}"

# ------------
# Lists
commands: []
docker_images: []

# Ignoring errors on personal repos so we can proceed when there are local changes
git_repos:
  - repo: "git@github.com:reynn/dotfiles.git"
    dest: "{{ dotfiles_path }}"
    ignore_errors: "yes"
  - repo: "git@github.com:powerline/fonts.git"
    dest: "{{ github_path }}/powerline/fonts"
  - repo: "git@github.com:junegunn/fzf.git"
    dest: "{{ github_path }}/junegunn/fzf"
    handler: "Run fzf install script"

# ------------
# Maps
packages:
  system:
    basic:
      - curl
      - wget
      - tmux
    pacman:
      - gcc
      - pulseaudio
      - pkg-config
      - openssl
      - make
      - cmake
    apt:
      - build-essential
    dnf: []
  pip:
    - ansible
    - certifi
    - httpie
    - docker
  cargo: []
  brew:
    - tmux

scripts:
  - name: "installer.starship"
    url: "https://raw.githubusercontent.com/starship/starship/master/install/install.sh"
  - name: "installer.spacevim"
    url: "https://raw.githubusercontent.com/SpaceVim/SpaceVim/master/docs/install.sh"
  - name: "installer.rustup"
    url: "https://raw.githubusercontent.com/rust-lang/rustup/master/rustup-init.sh"

to_create:
  - dest: "{{ ansible_user_dir }}/.ssh"
    state: "directory"
  - dest: "{{ ansible_user_dir }}/.ssh/keys"
    state: "directory"
  - dest: "{{ ansible_user_dir }}/.config"
    state: "directory"
  - dest: "{{ ansible_user_dir }}/.config/fish"
    state: "directory"
  - dest: "{{ ansible_user_dir }}/.config/fish/config.fish"
    src: "{{ dotfiles_path }}/configs/fish/config.fish"
    state: "link"
  - dest: "{{ ansible_user_dir }}/.config/fish/fish_plugins"
    src: "{{ dotfiles_path }}/configs/fish/fish_plugins"
    state: "link"
  - dest: "{{ ansible_user_dir }}/.SpaceVim.d"
    src: "{{ dotfiles_path }}/configs/spacevim"
    state: "link"
  - dest: "{{ ansible_user_dir }}/.config/nvim"
    src: "{{ ansible_user_dir }}/.SpaceVim"
    state: "link"
  - dest: "{{ ansible_user_dir }}/.gitconfig"
    src: "{{ dotfiles_path }}/configs/git/gitconfig"
    state: "link"
  - dest: "{{ github_path }}/.gitconfig"
    src: "{{ dotfiles_path }}/configs/git/public_github"
    state: "link"
  - dest: "{{ ansible_user_dir }}/.config/alacritty"
    src: "{{ dotfiles_path }}/configs/alacritty"
    state: "link"
