# ------------
# Strings

bins_dir: "{{ ansible_user_dir }}/.local/bin"
git_path: "{{ ansible_user_dir }}/git"
github_path: "{{ git_path }}/github.com"
dotfiles_path: "{{ github_path }}/reynn/dotfiles"

# ------------
# Secrets
ssh_keys: "{{ vault_ssh_keys }}"
ssh_hosts: "{{ vault_ssh_hosts }}"

# ------------
# Lists
commands: []
docker_images: []

# Ignoring errors on personal repos so we can proceed when there are local changes
git_repos:
  - repo: "git@github.com:reynn/dotfiles.git"
    dest: "{{ dotfiles_path }}"
    ignore_errors: "yes"

# ------------
# Maps
packages:
  cargo:
    - name: cargo-edit
      default_features: false
      features:
        - vendored-openssl
    - name: lsd
    - name: vers
    - name: skim
    - name: ripgrep
  go:
    - github.com/loov/goda@latest
    - github.com/charmbracelet/gum@latest
  npm:
    - yarn
    - quicktype
  pip:
    - ansible
    - certifi
    - httpie
    - pre-commit
  system:
    brew:
      - graphviz
    basic:
      - curl
      - wget
      - zip
      - unzip
    pacman:
      - gcc
      - pulseaudio
      - pkg-config
      - openssl
      - make
      - cmake
    apt:
      - build-essential
      - pkg-config
      - libssl-dev
    dnf: []

scripts:
  - name: installer.rustup
    url: https://raw.githubusercontent.com/rust-lang/rustup/master/rustup-init.sh
  - name: installer.lunarvim
    url: https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh

to_create:
  - dest: "{{ ansible_user_dir }}/.ssh"
    state: directory
  - dest: "{{ ansible_user_dir }}/.ssh/keys"
    state: directory
  - dest: "{{ ansible_user_dir }}/.config"
    state: directory
  - dest: "{{ ansible_user_dir }}/.config/fish"
    state: directory
  - dest: "{{ ansible_user_dir }}/.config/fish/config.fish"
    src: "{{ dotfiles_path }}/configs/fish/config.fish"
    state: link
  - dest: "{{ ansible_user_dir }}/.config/fish/fish_plugins"
    src: "{{ dotfiles_path }}/configs/fish/fish_plugins"
    state: link
  - dest: "{{ github_path }}/.gitconfig"
    src: "{{ dotfiles_path }}/configs/git/public_github"
    state: link
  - dest: "{{ ansible_user_dir }}/.config/alacritty"
    src: "{{ dotfiles_path }}/configs/alacritty"
    state: link
  - dest: "{{ ansible_user_dir }}/.config/wezterm"
    src: "{{ dotfiles_path }}/configs/wezterm"
    state: link
  - dest: "{{ ansible_user_dir }}/.config/lsd"
    src: "{{ dotfiles_path }}/configs/lsd"
    state: link
  - dest: "{{ ansible_user_dir }}/revive.toml"
    src: "{{ dotfiles_path }}/configs/revive.toml"
    state: link
