# ------------
# Strings

bins_dir: "{{ ansible_user_dir }}/.bins"
git_path: "{{ ansible_user_dir }}/git"
github_path: "{{ git_path }}/github.com"
dotfiles_path: "{{ github_path }}/reynn/dotfiles"

# ------------
# Secrets
ssh_keys: "{{ vault_ssh_keys }}"
ssh_hosts: "{{ vault_ssh_hosts }}"

# ------------
# Lists
commands: []
docker_images: []

# Ignoring errors on personal repos so we can proceed when there are local changes
git_repos:
  - repo: "git@github.com:reynn/dotfiles.git"
    dest: "{{ dotfiles_path }}"
    ignore_errors: "yes"
  - repo: "git@github.com:ryanoasis/nerd-fonts.git"
    dest: "{{ github_path }}/ryanoasis/nerd-fonts"
    handler: "Install fonts from `ryanoasis/nerd-fonts`"

# ------------
# Maps
packages:
  brew: []
  cargo:
    - name: cargo-edit
      default_features: false
      features:
        - vendored-openssl
  go: []
  npm:
    - "yarn"
    - "@bitwarden/cli"
    - "quicktype"
  pip:
    - ansible
    - certifi
    - httpie
    - pre-commit
  system:
    basic:
      - curl
      - wget
      - tmux
    pacman:
      - gcc
      - pulseaudio
      - pkg-config
      - openssl
      - make
      - cmake
    apt:
      - build-essential
    dnf: []

scripts:
  - name: installer.spacevim
    url: "https://raw.githubusercontent.com/SpaceVim/SpaceVim/master/docs/install.sh"
  - name: installer.rustup
    url: "https://raw.githubusercontent.com/rust-lang/rustup/master/rustup-init.sh"

to_create:
  - dest: "{{ ansible_user_dir }}/.ssh"
    state: directory
  - dest: "{{ ansible_user_dir }}/.ssh/keys"
    state: directory
  - dest: "{{ ansible_user_dir }}/.config"
    state: directory
  - dest: "{{ ansible_user_dir }}/.config/fish"
    state: directory
  - dest: "{{ ansible_user_dir }}/.config/fish/config.fish"
    src: "{{ dotfiles_path }}/configs/fish/config.fish"
    state: link
  - dest: "{{ ansible_user_dir }}/.config/fish/fish_plugins"
    src: "{{ dotfiles_path }}/configs/fish/fish_plugins"
    state: link
  - dest: "{{ ansible_user_dir }}/.gitconfig"
    src: "{{ dotfiles_path }}/configs/git/gitconfig"
    state: link
  - dest: "{{ github_path }}/.gitconfig"
    src: "{{ dotfiles_path }}/configs/git/public_github"
    state: link
  - dest: "{{ ansible_user_dir }}/.config/alacritty"
    src: "{{ dotfiles_path }}/configs/alacritty"
    state: link
