---
- hosts: localhost

  tasks:
    - name: Include vars from ansible directory
      include_vars:
        dir: ansible/vars
        extensions:
          - yaml
          - yml
      tags:
        - always

    - name: Install packages
      package:
        name: "{{ packages.system }}"
        state: present
      when:
        - ansible_system == 'Linux'
      become: yes

    - name: "Link .zshrc file"
      file:
        src: "{{ ansible_env.PWD }}/zsh/.zshrc"
        dest: "{{ ansible_env.HOME }}/.zshrc"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        state: link

    - name: Clone git repos
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        depth: 1
      loop: "{{ git_repos }}"

    - name: Run fzf install script
      shell: "{{ git_path }}/junegunn/fzf/install --bin --64"

    - name: Ensure binary dirs exist
      file:
        path: "{{ binary_dir | default(ansible_env.HOME + '/.bins') }}"
        state: directory
        mode: 0755
      tags:
        - binaries
        - update

    - include_tasks: "{{ ansible_env.PWD }}/ansible/get-latest-release-from-github.yaml"
      with_items: "{{ bin_downloads }}"
      tags:
        - binaries
        - update

    - name: Installing pip packages
      pip:
        name: "{{ packages.pip }}"
        state: latest
        extra_args: --user
      # loop: "{{ packages.pip }}"
      tags:
        - pip
        - update

    - name: Set the default shell to zsh
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
