return {
	g = {
		gruvbox_baby_telescope_theme = 1,
		gruvbox_baby_background_color = "medium",
		gruvbox_baby_comment_style = "italic",
		gruvbox_baby_function_style = "bold",
		gruvbox_baby_keyword_style = "bold",
		gruvbox_baby_variable_style = "standout",

		tokyodark_enable_italic_comment = true,
		tokyodark_enable_italic = true,
	},
	opt = {
		conceallevel = 2,
		fillchars = {
			horiz = "━",
			horizup = "┻",
			horizdown = "┳",
			vert = "┃",
			vertleft = "┨",
			vertright = "┣",
			verthoriz = "╋",
		},
		foldenable = false,
		foldexpr = "nvim_treesitter#foldexpr()",
		foldmethod = "expr",
		laststatus = 3,
		list = false,
		listchars = {
			tab = "→ ",
			extends = "⟩",
			precedes = "⟨",
			trail = "·",
			nbsp = "␣",
			eol = "↲",
		},
		numberwidth = 2,
		relativenumber = true,
		scrolloff = 10,
		showbreak = "↪ ",
		sidescrolloff = 15,
		timeoutlen = 100,
		updatetime = 100,
		wrap = false,
	},
}
