return {
	opt = {
		fillchars = {
			horiz = "━",
			horizup = "┻",
			horizdown = "┳",
			vert = "┃",
			vertleft = "┨",
			vertright = "┣",
			verthoriz = "╋",
		},
		foldenable = false,
		foldexpr = "nvim_treesitter#foldexpr()",
		foldmethod = "expr",
		laststatus = 3,
		list = false,
		listchars = {
			tab = "→ ",
			extends = "⟩",
			precedes = "⟨",
			trail = "·",
			nbsp = "␣",
			eol = "↲",
		},
		numberwidth = 4,
		relativenumber = true,
		scrolloff = 10,
		showbreak = "↪ ",
		sidescrolloff = 15,
		timeoutlen = 100,
		updatetime = 100,
		conceallevel = 2,
	},
}
