apiVersion: v1
kind: Pod
metadata:
  name: golang-test-pod
  labels:
    name: golang-test-pod
spec:
  containers:
  - name: golang-test-pod
    image: golang:1.12-stretch
    command: ["/bin/bash"]
    args:
      - "-c"
      - "sleep 40000"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
