---
extra_to_create:
  - dest: "{{ ansible_user_dir }}/.config/systemd"
    state: "directory"
  - src: "{{ dotfiles_path }}/configs/systemd"
    dest: "{{ ansible_user_dir }}/.config/systemd/user"
    state: "link"
