# All SpaceVim option below [option] section
[options]
# autocomplete_method = 'coc'
automatic_update              = true
colorscheme                   = 'gruvbox'
colorscheme_bg                = 'dark'
enable_guicolors              = true
enable_statusline_mode        = false
enable_tabline_filetype_icon  = true
filemanager                   = 'nerdtree'
guifont                       = 'SourceCodePro Nerd Font Mono:h11'
statusline_inactive_separator = 'arrow'
statusline_separator          = 'arrow'

[[layers]]
name = 'colorscheme'

[[layers]]
filetree_show_hidden = true
name                 = 'core'

# Enable autocomplete layer
[[layers]]
auto_completion_return_key_behavior = 'smart'
auto_completion_tab_key_behavior    = 'smart'
name                                = 'autocomplete'

[[layers]]
default_height   = 30
default_position = 'top'
name             = 'shell'

[[layers]]
name = "ctrlp"

[[layers]]
filetypes = ['rust']
name      = 'lsp'

  [layers.override_cmd]
  rust = ['rust-analyzer']

[[layers]]
name = "lang#csharp"

[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = "lang#extra"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#groovy"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#python"

[[layers]]
name = 'lang#rust'

[[layers]]
name = 'lang#toml'
