# ------------
# Strings
bins_dir: "{{ ansible_env.HOME }}/.bins"
git_path: "{{ ansible_env.HOME }}/git"
dotfiles_path: "{{ git_path }}/github.com/reynn/dotfiles"

# ------------
# Maps
packages:
  system:
    - zsh
    - git
    - curl
    - wget
    - tmux
  pip:
    - certifi
    - httpie
    - Pygments
    - yq

# ------------
# Lists
bin_downloads:
  - repository: api.github.com/BurntSushi/ripgrep
    alias: rg
  - repository: api.github.com/stedolan/jq
  - repository: api.github.com/ogham/exa
  - repository: api.github.com/GoogleContainerTools/skaffold
  - repository: api.github.com/goreleaser/goreleaser
  - repository: api.github.com/kubernetes/minikube
  - repository: api.github.com/rancher/rio
  - repository: api.github.com/digitalocean/doctl
  # - repository: api.github.com/derailed/k9s # Commented out, all releases currently marked as pre-release
  - repository: api.github.com/wercker/stern
  - repository: api.github.com/goodwithtech/dockle
  - repository: api.github.com/k14s/kwt
  - repository: api.github.com/k14s/kapp
  - repository: api.github.com/k14s/kbld
  - repository: api.github.com/k14s/ytt
  - repository: api.github.com/starship/starship
  - repository: api.github.com/linkerd/linkerd2
    alias: linkerd
  - repository: api.github.com/sharkdp/fd
git_repos:
  - repo: git@github.com:reynn/dotfiles.git
    dest: "{{ dotfiles_path }}"
  - repo: git@github.com:reynn/k8s.git
    dest: "{{ git_path }}/github.com/reynn/k8s"
  - repo: git@github.com:helm/charts.git
    dest: "{{ git_path }}/github.com/helm/charts"
  - repo: git@github.com:thecasualcoder/kube-fzf.git
    dest: "{{ git_path }}/github.com/thecasualcoder/kube-fzf"
  - repo: git@github.com:mbadolato/iTerm2-Color-Schemes.git
    dest: "{{ git_path }}/github.com/mbadolato/iterm2-color"
  - repo: git@github.com:powerline/fonts.git
    dest: "{{ git_path }}/github.com/powerline/fonts"
  - repo: git@github.com:junegunn/fzf.git
    dest: "{{ git_path }}/github.com/junegunn/fzf"
  - repo: git@github.com:VundleVim/Vundle.vim.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"
commands:
  - cmd: "go build -o {{ bins_dir }}/helpers main.go"
    dir: "{{ dotfiles_path }}/go/helpers"
  - cmd: "sh /tmp/antibody -b {{ bins_dir }}"
scripts:
  - name: gimme
    url: https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
    dir: "{{ bins_dir }}"
  - name: antibody
    url: https://git.io/antibody
    dir: /tmp
  - name: nvm
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh
    dir: "{{ bins_dir }}"
  - name: kubectx
    url: https://raw.githubusercontent.com/ahmetb/kubectx/master/kubectx
    dir: "{{ bins_dir }}"
  - name: kubens
    url: https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens
    dir: "{{ bins_dir }}"
