packages:
  system:
    - zsh
    - git
    - curl
    - wget
    - tmux
  pip:
    - Pygments
    - yq
git_path: "{{ ansible_env.HOME }}/git"
dotfiles_path: "{{ git_path }}/reynn/dotfiles"
git_repos:
  - repo: https://github.com/reynn/dotfiles.git
    dest: "{{ git_path }}/reynn/dotfiles"
  - repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ git_path }}/robbyrussell/oh-my-zsh"
  - repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "{{ git_path }}/robbyrussell/oh-my-zsh/custom/themes/powerlevel9k"
  - repo: https://github.com/mbadolato/iTerm2-Color-Schemes.git
    dest: "{{ git_path }}/mbadolato/iterm2-color"
  - repo: https://github.com/powerline/fonts.git
    dest: "{{ git_path }}/powerline/fonts"
  - repo: https://github.com/junegunn/fzf.git
    dest: "{{ git_path }}/junegunn/fzf"
bin_downloads:
  - name: Ripgrep
    git:
      owner: BurntSushi
      repo: ripgrep
    alias: rg
  - name: JQ
    git:
      owner: stedolan
      repo: jq
