# ------------
# Strings
bins_dir: "{{ ansible_env.HOME }}/.bins"
git_path: "{{ ansible_env.HOME }}/git"
dotfiles_path: "{{ git_path }}/reynn/dotfiles"

# ------------
# Maps
packages:
  system:
    - zsh
    - git
    - curl
    - wget
    - tmux
  pip:
    - certifi
    - Pygments
    - yq

# ------------
# Lists
bin_downloads:
  - name: Ripgrep
    git:
      owner: BurntSushi
      repo: ripgrep
    alias: rg
  - name: JQ
    git:
      owner: stedolan
      repo: jq
  - name: exa
    git:
      owner: ogham
      repo: exa
  - name: skaffold
    git:
      owner: GoogleContainerTools
      repo: skaffold
  - name: goreleaser
    git:
      owner: goreleaser
      repo: goreleaser
  - name: minikube
    git:
      owner: kubernetes
      repo: minikube
  - name: rio
    git:
      owner: rancher
      repo: rio
  - name: doctl
    git:
      owner: digitalocean
      repo: doctl
  # - name: k9s # Commented out, all releases currently marked as pre-release
  #   git:
  #     owner: derailed
  #     repo: k9s
  - name: stern
    git:
      owner: wercker
      repo: stern
  - name: dockle
    git:
      owner: goodwithtech
      repo: dockle
  - name: linkerd2
    git:
      owner: linkerd
      repo: linkerd2
    alias: linkerd
git_repos:
  - repo: git@github.com:reynn/dotfiles.git
    dest: "{{ git_path }}/github.com/reynn/dotfiles"
  - repo: git@github.com:reynn/k8s.git
    dest: "{{ git_path }}/github.com/reynn/k8s"
  - repo: git@github.com:thecasualcoder/kube-fzf.git
    dest: "{{ git_path }}/github.com/thecasualcoder/kube-fzf"
  - repo: git@github.com:mbadolato/iTerm2-Color-Schemes.git
    dest: "{{ git_path }}/github.com/mbadolato/iterm2-color"
  - repo: git@github.com:powerline/fonts.git
    dest: "{{ git_path }}/github.com/powerline/fonts"
  - repo: git@github.com:junegunn/fzf.git
    dest: "{{ git_path }}/github.com/junegunn/fzf"
commands:
  - cmd: "go build -o {{ bins_dir }}/helpers main.go"
    dir: "{{ git_path }}/github.com/reynn/dotfiles/go/helpers"
scripts:
  - name: gimme
    url: https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - name: nvm
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh
  - name: kubectx
    url: https://raw.githubusercontent.com/ahmetb/kubectx/master/kubectx
  - name: kubens
    url: https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens
