# ------------
# Strings

bins_dir: "{{ ansible_env.HOME }}/.bins"
git_path: "{{ ansible_env.HOME }}/git"
github_path: "{{ git_path }}/github.com"
dotfiles_path: "{{ github_path }}/reynn/dotfiles"

# ------------
# Lists
commands: []
docker_images: []

# Ignoring errors on personal repos so we can proceed when there are local changes
git_repos:
  - repo: "git@github.com:reynn/dotfiles.git"
    dest: "{{ dotfiles_path }}"
    ignore_errors: "yes"
  - repo: "git@github.com:reynn/k8s.git"
    dest: "{{ github_path }}/reynn/k8s"
    ignore_errors: "yes"
  - repo: "git@github.com:reynn/k8s-ops.git"
    dest: "{{ github_path }}/reynn/k8s-ops"
    ignore_errors: "yes"
  - repo: "git@github.com:mbadolato/iTerm2-Color-Schemes.git"
    dest: "{{ github_path }}/mbadolato/iterm2-color"
  - repo: "git@github.com:powerline/fonts.git"
    dest: "{{ github_path }}/powerline/fonts"
  - repo: "git@github.com:junegunn/fzf.git"
    dest: "{{ github_path }}/junegunn/fzf"
    handler: "Run fzf install script"
  - repo: "git@github.com:tmux-plugins/tpm"
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

# ------------
# Maps
packages:
  system:
    basic:
      - curl
      - wget
      - tmux
    pacman:
      - gcc
      - pulseaudio
      - pkg-config
      - openssl
      - make
      - cmake
    apt:
      - build-essential
    dnf: []
  pip:
    - ansible
    - certifi
    - httpie
    - docker
  cargo: []
  brew:
    - tmux

scripts:
  - name: "gimme"
    url: "https://raw.githubusercontent.com/travis-ci/gimme/master/gimme"
  - name: "installer.starship"
    url: "https://raw.githubusercontent.com/starship/starship/master/install/install.sh"
  - name: "installer.spacevim"
    url: "https://raw.githubusercontent.com/SpaceVim/SpaceVim/master/docs/install.sh"
  - name: "installer.rustup"
    url: "https://raw.githubusercontent.com/rust-lang/rustup/master/rustup-init.sh"

to_create:
  - dest: "{{ ansible_env.HOME }}/.config"
    state: "directory"
  - dest: "{{ ansible_env.HOME }}/.config/fish"
    src: "{{ dotfiles_path }}/configs/fish"
    state: "link"
  - dest: "{{ ansible_env.HOME }}/.SpaceVim.d"
    src: "{{ dotfiles_path }}/configs/spacevim"
    state: "link"
  - dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    src: "{{ dotfiles_path }}/configs/starship/config.toml"
    state: "link"
  - dest: "{{ ansible_env.HOME }}/.config/nvim"
    src: "{{ ansible_env.HOME }}/.SpaceVim"
    state: "link"
  - dest: "{{ ansible_env.HOME }}/.gitconfig"
    src: "{{ dotfiles_path }}/configs/git/gitconfig"
    state: "link"
  - dest: "{{ ansible_env.HOME }}/.tmux.conf"
    src: "{{ dotfiles_path }}/configs/tmux/tmux.conf"
    state: "link"
