# ------------
# Strings
bins_dir: "{{ ansible_env.HOME }}/.bins"
git_path: "{{ ansible_env.HOME }}/git"
dotfiles_path: "{{ git_path }}/github.com/reynn/dotfiles"

file_links:
  - src: ".zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
  - src: ".vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"

# ------------
# Maps
packages:
  system:
    - zsh
    - git
    - curl
    - wget
    - tmux
  pip:
    - certifi
    - httpie
    - Pygments
    - yq
    - pipenv
    - youtube_dl
    - pipenv
    - docker
  cargo:
    - broot
    - exa
    - ripgrep
  brew:
    - tmux
    - zsh
    - pyenv

# ------------
# Lists
# TODO: Add alternate filter option for Canop/broot
# TODO: Add ability to pull pre-releases
# TODO: Add ability to overwrite to specific arch/prefix for linkerd2
bin_downloads:
  - repository: sharkdp/bat
    description: A cat(1) clone with wings
  - repository: goodwithtech/dockle
    description: Container Image Linter for Security
  - repository: digitalocean/doctl
    description: Digital Ocean CLI
  - repository: sharkdp/fd
    description: A simple, fast and user-friendly alternative to 'find'
  - repository: goreleaser/goreleaser
    description: Deliver Go binaries as fast and easily as possible
  - repository: stedolan/jq
    description: CLI JSON processor
  # - repository: derailed/k9s
  #   description: Kubernetes CLI To Manage Your Clusters In Style!
  - repository: k14s/kapp
    description: A simple deployment tool focused on the concept of "Kubernetes application"
  - repository: k14s/kbld
    description: Image building and pushing
  - repository: k14s/kwt
    description: Kubernetes Workstation Tools CLI
  - repository: k14s/ytt
    description: YAML templating tool that works on YAML structure instead of text
  - repository: helm/helm
    description: Kubernetes Workstation Tools CLI
  # - repository: linkerd/linkerd2
  #   description: A service mesh for Kubernetes and beyond
  #   alias: linkerd
  - repository: kubernetes/minikube
    description: Run Kubernetes locally
  - repository: ryochack/peep
    description: The CLI text viewer tool that works like less command on small pane within the terminal window
  - repository: rancher/rio
    description: Kubernetes based MicroPaaS (Adds additional features to Kubernetes)
  - repository: GoogleContainerTools/skaffold
    description: Easy and Repeatable Kubernetes Development
  - repository: starship/starship
    description: The cross-shell prompt for astronauts
  - repository: wercker/stern
    description: K8s logging helper
docker_images:
  - name: fantia.jp
    source: build
    build:
      pull: yes
      path: "{{ dotfiles_path }}/docker/fantia.jp"
  - name: pixiv
    source: build
    build:
      pull: yes
      path: "{{ dotfiles_path }}/docker/pixiv"
  - name: yiff.party
    source: build
    build:
      pull: yes
      path: "{{ dotfiles_path }}/docker/yiff.party"

git_repos:
  - repo: git@github.com:reynn/dotfiles.git
    dest: "{{ dotfiles_path }}"
  - repo: git@github.com:reynn/k8s.git
    dest: "{{ git_path }}/github.com/reynn/k8s"
  - repo: git@github.com:helm/charts.git
    dest: "{{ git_path }}/github.com/helm/charts"
  - repo: git@github.com:thecasualcoder/kube-fzf.git
    dest: "{{ git_path }}/github.com/thecasualcoder/kube-fzf"
  - repo: git@github.com:mbadolato/iTerm2-Color-Schemes.git
    dest: "{{ git_path }}/github.com/mbadolato/iterm2-color"
  - repo: git@github.com:powerline/fonts.git
    dest: "{{ git_path }}/github.com/powerline/fonts"
  - repo: git@github.com:junegunn/fzf.git
    dest: "{{ git_path }}/github.com/junegunn/fzf"
  - repo: git@github.com:VundleVim/Vundle.vim.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"
commands:
  - cmd: "go build -o {{ bins_dir }}/helpers main.go"
    dir: "{{ dotfiles_path }}/go/helpers"
  - cmd: "sh /tmp/antibody -b {{ bins_dir }}"
scripts:
  - name: gimme
    url: https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
    dir: "{{ bins_dir }}"
  - name: antibody
    url: https://git.io/antibody
    dir: /tmp
  - name: nvm
    url: https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh
    dir: "{{ bins_dir }}"
  - name: kubectx
    url: https://raw.githubusercontent.com/ahmetb/kubectx/master/kubectx
    dir: "{{ bins_dir }}"
  - name: kubens
    url: https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens
    dir: "{{ bins_dir }}"
