# ------------
# Strings
bins_dir: "{{ ansible_env.HOME }}/.bins"
git_path: "{{ ansible_env.HOME }}/git"
dotfiles_path: "{{ git_path }}/github.com/reynn/dotfiles"

# ------------
# Maps
packages:
  system:
    - zsh
    - git
    - curl
    - wget
    - tmux
  pip:
    - certifi
    - httpie
    - Pygments
    - yq

# ------------
# Lists
bin_downloads:
  - repository: api.github.com/sharkdp/bat                    # A cat(1) clone with wings.
  - repository: api.github.com/Canop/broot                    # A new way to see and navigate directory trees
  - repository: api.github.com/goodwithtech/dockle            # Container Image Linter for Security
  - repository: api.github.com/digitalocean/doctl             # Digital Ocean CLI
  - repository: api.github.com/ogham/exa                      # A modern version of ‘ls’.
  - repository: api.github.com/sharkdp/fd                     # A simple, fast and user-friendly alternative to 'find'
  - repository: api.github.com/goreleaser/goreleaser          # Deliver Go binaries as fast and easily as possible
  - repository: api.github.com/stedolan/jq                    # CLI JSON processor
  - repository: api.github.com/derailed/k9s                   # Kubernetes CLI To Manage Your Clusters In Style!
  - repository: api.github.com/k14s/kapp                      # A simple deployment tool focused on the concept of "Kubernetes application"
  - repository: api.github.com/k14s/kbld                      # Image building and pushing
  - repository: api.github.com/k14s/kwt                       # Kubernetes Workstation Tools CLI
  - repository: api.github.com/linkerd/linkerd2               # A service mesh for Kubernetes and beyond
    alias: linkerd
  - repository: api.github.com/kubernetes/minikube            # Run Kubernetes locally
  - repository: api.github.com/ryochack/peep                  # The CLI text viewer tool that works like less command on small pane within the terminal window.
  - repository: api.github.com/rancher/rio                    # Kubernetes based MicroPaaS (Adds additional features to Kubernetes)
  - repository: api.github.com/BurntSushi/ripgrep             # recursively searches directories for a regex pattern
    alias: rg
  - repository: api.github.com/GoogleContainerTools/skaffold  # Easy and Repeatable Kubernetes Development
  - repository: api.github.com/starship/starship              # The cross-shell prompt for astronauts.
  - repository: api.github.com/wercker/stern                  # K8s logging helper
  - repository: api.github.com/k14s/ytt                       # YAML templating tool that works on YAML structure instead of text
git_repos:
  - repo: git@github.com:reynn/dotfiles.git
    dest: "{{ dotfiles_path }}"
  - repo: git@github.com:reynn/k8s.git
    dest: "{{ git_path }}/github.com/reynn/k8s"
  - repo: git@github.com:helm/charts.git
    dest: "{{ git_path }}/github.com/helm/charts"
  - repo: git@github.com:thecasualcoder/kube-fzf.git
    dest: "{{ git_path }}/github.com/thecasualcoder/kube-fzf"
  - repo: git@github.com:mbadolato/iTerm2-Color-Schemes.git
    dest: "{{ git_path }}/github.com/mbadolato/iterm2-color"
  - repo: git@github.com:powerline/fonts.git
    dest: "{{ git_path }}/github.com/powerline/fonts"
  - repo: git@github.com:junegunn/fzf.git
    dest: "{{ git_path }}/github.com/junegunn/fzf"
  - repo: git@github.com:VundleVim/Vundle.vim.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"
commands:
  - cmd: "go build -o {{ bins_dir }}/helpers main.go"
    dir: "{{ dotfiles_path }}/go/helpers"
  - cmd: "sh /tmp/antibody -b {{ bins_dir }}"
scripts:
  - name: gimme
    url: https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
    dir: "{{ bins_dir }}"
  - name: antibody
    url: https://git.io/antibody
    dir: /tmp
  - name: nvm
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh
    dir: "{{ bins_dir }}"
  - name: kubectx
    url: https://raw.githubusercontent.com/ahmetb/kubectx/master/kubectx
    dir: "{{ bins_dir }}"
  - name: kubens
    url: https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens
    dir: "{{ bins_dir }}"
