#!/usr/bin/env zsh

local remove_archive
local success
local extract_dir
if (($# == 0)); then
  cat <<'EOF' >&2
Usage: extract [-option] [file]

Options:
    -r, --remove      Remove archive after unpacking.
    -d, --directory   The extract directory.
EOF
fi

remove_archive=1
if [[ "$1" == "-r" ]] || [[ "$1" == "--remove" ]]; then
  remove_archive=0
  shift
fi
if [[ "$1" == "-d" ]] || [[ "$1" == "--directory" ]]; then
  extract_dir=$2
  shift
  shift
fi
while (($# > 0)); do
  if [[ ! -f "$1" ]]; then
    echo "extract: '$1' is not a valid file" >&2
    shift
    continue
  fi
  local success=0
  # input filename, tail,
  local extract_dir="${1:h}"
  local extension="${1:l}"
  echo "zsh.extract.dir: $extract_dir" >&2
  echo "zsh.extract.extension: $extension" >&2
  case $extension in
  *.tar.gz | *.tgz) (($ + commands[pigz])) && {
    pigz -dc "$1" | tar xv
  } || tar zxvf "$1" ;;
  *.tar.bz2 | *.tbz | *.tbz2) tar xvjf "$1" ;;
  *.tar.xz | *.txz) tar --xz --help &>/dev/null && tar --xz -xvf "$1" || xzcat "$1" | tar xvf - ;;
  *.tar.zma | *.tlz) tar --lzma --help &>/dev/null && tar --lzma -xvf "$1" || lzcat "$1" | tar xvf - ;;
  *.tar.zst | *.tzst) tar --zstd --help &>/dev/null && tar --zstd -xvf "$1" || zstdcat "$1" | tar xvf - ;;
  *.tar) tar xvf "$1" ;;
  *.tar.lz) (($ + commands[lzip])) && tar xvf "$1" ;;
  *.tar.lz4) lz4 -c -d "$1" | tar xvf - ;;
  *.tar.lrz) (($ + commands[lrzuntar])) && lrzuntar "$1" ;;
  *.gz) (($ + commands[pigz])) && pigz -dk "$1" || gunzip -k "$1" ;;
  *.bz2) bunzip2 "$1" ;;
  *.xz) unxz "$1" ;;
  *.lrz) (($ + commands[lrunzip])) && lrunzip "$1" ;;
  *.lz4) lz4 -d "$1" ;;
  *.lzma) unlzma "$1" ;;
  *.z) uncompress "$1" ;;
  *.zip | *.war | *.jar | *.sublime-package | *.ipsw | *.xpi | *.apk | *.aar | *.whl) unzip $1 -d $extract_dir ;;
  *.rar) unrar x -ad "$1" ;;
  *.7z) 7za x "$1" ;;
  *.zst) unzstd "$1" ;;
  *)
    echo "extract: '$1' cannot be extracted" >&2
    success=1
    ;;
  esac
  ((success = $success > 0 ? $success : $?))
  (($success == 0)) && (($remove_archive == 0)) && rm -i "$1"
  shift
done
