#!/usr/bin/env zsh

# Initialize this dotfile repo as well as run updates when necessary

typeset -A styles=(
  [full]='Sources all zsh files to refresh aliases/exports/functions'
  [aliases]='Sources just the aliases from the zsh directory'
  [exports]='Sources just the aliases from the zsh directory'
  [functions]='Sources just the aliases from the zsh directory'
)

SCRIPT_NAME="${0:t:r}"
DEBUG='false'

function __print_help {
  echo "Usage: $SCRIPT_NAME [ -s STYLE ]"
  echo '----------------------------------------------------------------'
  echo 'Available styles:'
  for key in ${(kO)styles}; do
    echo "$key: ${styles[$key]}"
  done
}

function __get_files {
  local filter="$1"
  local path="$2"
  $DIR_BINS/fd -t f $filter $path
}

function __import {
  local f="$1"
  print_debug $f '__import'
  source $f
}

function handle_aliases {
  echo 'Initializing aliases...'
  for alias in $(__get_files '.+\.zsh' $DFP/zsh/aliases/); do
    __import "$alias"
  done
}

function handle_exports {
  echo 'Initializing exports...'
  for exportable in $(__get_files '.+\.zsh' $DFP/zsh/.vars/); do
    __import "$exportable"
  done
}

function handle_functions {
  echo 'Initializing functions...'
  for func in $(__get_files '.+\.zsh' $DFP/zsh/functions/); do
    __import "$func"
  done
}

function main {
  while getopts "hvs:" opt; do
    case $opt in
      s) STYLE="$OPTARG" ;;
      v) DEBUG='true' ;;
      h)
        __print_help
        exit 0
        ;;
    esac
  done

  case $STYLE in
    full | all)
      echo 'Starting full initialization sequence...'
      handle_aliases
      handle_exports
      handle_functions
      echo 'Completed!'
    ;;
    aliases) handle_aliases ;;
    functions) handle_functions ;;
    exports) handle_exports ;;
    *)
      __print_help
      echo '----------------------------------------------------------------'
      echo "Unknown style, use one from the list above"
      exit 1
      ;;
  esac
}

main $@
