---
- hosts: localhost
  force_handlers: true
  gather_facts: true

  pre_tasks:
    - add_host:
        name: "localhost"
        groups:
          - "{{ ansible_os_family | lower }}"
      tags:
        - always
    - gather_facts:
      tags:
        - always

  roles:
    - base
