all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      ansible_connection: local
      ansible_python_interpreter: /usr/local/bin/python3
    mimikyu:
      ansible_host: mimikyu

media_server:
  hosts:
    mimikyu:
