font:
  size: 16
  normal:
    family: Hasklug Nerd Font
    style: Regular
  bold:
    family: Hasklug Nerd Font
    style: Bold
  italic:
    family: Hasklug Nerd Font
    style: Italic

# -----------------------------------------------------------------------------
# use `xxd -psd` to determine key codes
# -----------------------------------------------------------------------------
key_bindings:
  []
  # ----------- Fish bindings -------------------------------------------------
  #
  #- { key: Z, mods: Command, chars: "\x66\x67\x0a" }

window:
  # Window dimensions (changes require restart)
  dimensions:
    columns: 140
    lines: 45

cursor:
  style: Block

hide_cursor_while_typing: false

color_schemes:
  afterglow: &afterglow
    primary:
      background: "#2c2c2c"
      foreground: "#d6d6d6"
      dim_foreground: "#dbdbdb"
      bright_foreground: "#d9d9d9"
      dim_background: "#202020" # not sure
      bright_background: "#3a3a3a" # not sure
    cursor:
      text: "#2c2c2c"
      cursor: "#d9d9d9"
    normal:
      black: "#1c1c1c"
      red: "#bc5653"
      green: "#909d63"
      yellow: "#ebc17a"
      blue: "#7eaac7"
      magenta: "#aa6292"
      cyan: "#86d3ce"
      white: "#cacaca"
    bright:
      black: "#636363"
      red: "#bc5653"
      green: "#909d63"
      yellow: "#ebc17a"
      blue: "#7eaac7"
      magenta: "#aa6292"
      cyan: "#86d3ce"
      white: "#f7f7f7"
    dim:
      black: "#232323"
      red: "#74423f"
      green: "#5e6547"
      yellow: "#8b7653"
      blue: "#556b79"
      magenta: "#6e4962"
      cyan: "#5c8482"
      white: "#828282"
  ayu_dark: &ayu_dark
    primary:
      background: "#0A0E14"
      foreground: "#B3B1AD"
    normal:
      black: "#01060E"
      red: "#EA6C73"
      green: "#91B362"
      yellow: "#F9AF4F"
      blue: "#53BDFA"
      magenta: "#FAE994"
      cyan: "#90E1C6"
      white: "#C7C7C7"
    bright:
      black: "#686868"
      red: "#F07178"
      green: "#C2D94C"
      yellow: "#FFB454"
      blue: "#59C2FF"
      magenta: "#FFEE99"
      cyan: "#95E6CB"
      white: "#FFFFFF"
  gruvbox_flat_dark: &gruvbox_flat_dark
    primary:
      background: "#1d2021"
      foreground: "#d4be98"
    # Normal colors
    normal:
      black: "#1D2021"
      red: "#ea6962"
      green: "#a9b665"
      yellow: "#d8a657"
      blue: "#7daea3"
      magenta: "#d3869b"
      aqua: "#89b482"
      white: "#d4be98"
    # Bright colors
    bright:
      black: "#17191a"
      red: "#ea6962"
      green: "#a9b665"
      yellow: "#d8a657"
      blue: "#7daea3"
      magenta: "#d3869b"
      aqua: "#89b482"
      white: "#d4be98"
    indexed_colors:
      - { index: 16, color: "#e78a4e" }
      - { index: 17, color: "#c14a4a" }
  gruvbox_light: &gruvbox_light
    primary:
      # background: '#f9f5d7' # hard contrast
      background: "#fbf1c7" # standard
      # background: '#f2e5bc' # soft contrast
      foreground: "#282828"
    normal:
      black: "#fbf1c7"
      red: "#cc241d"
      green: "#98971a"
      yellow: "#d79921"
      blue: "#458588"
      magenta: "#b16286"
      cyan: "#689d6a"
      white: "#7c6f64"
    bright:
      black: "#928374"
      red: "#9d0006"
      green: "#79740e"
      yellow: "#b57614"
      blue: "#076678"
      magenta: "#8f3f71"
      cyan: "#427b58"
      white: "#3c3836"
  gruvbox_dark: &gruvbox_dark
    primary:
      background: "#1e1e1e"
      foreground: "#e6d4a3"
    bright:
      black: "#7f7061"
      blue: "#719586"
      cyan: "#7db669"
      green: "#aab01e"
      magenta: "#c77089"
      red: "#f73028"
      white: "#e6d4a3"
      yellow: "#f7b125"
    cursor:
      cursor: "#e6d4a3"
      text: "#1e1e1e"
    normal:
      black: "#1e1e1e"
      blue: "#377375"
      cyan: "#578e57"
      green: "#868715"
      magenta: "#a04b73"
      red: "#be0f17"
      white: "#978771"
      yellow: "#cc881a"
    selection:
      background: "#e6d4a3"
      text: "#534a42"
  material: &material
    primary:
      background: "#263238"
      foreground: "#eeffff"
    normal:
      black: "#000000" # Arbitrary
      red: "#e53935"
      green: "#91b859"
      yellow: "#ffb62c"
      blue: "#6182b8"
      magenta: "#ff5370" # Dark pink of the original material theme
      cyan: "#39adb5"
      white: "#a0a0a0" # Arbitrary
    bright:
      black: "#4e4e4e" # Arbitrary
      red: "#ff5370"
      green: "#c3e88d"
      yellow: "#ffcb6b"
      blue: "#82aaff"
      magenta: "#f07178" # Pink of the original material theme
      cyan: "#89ddff"
      white: "#ffffff" # Arbitrary
  snazzy: &snazzy
    primary:
      background: "#282a36"
      foreground: "#eff0eb"
    normal:
      black: "#282a36"
      red: "#ff5c57"
      green: "#5af78e"
      yellow: "#f3f99d"
      blue: "#57c7ff"
      magenta: "#ff6ac1"
      cyan: "#9aedfe"
      white: "#f1f1f0"
    bright:
      black: "#686868"
      red: "#ff5c57"
      green: "#5af78e"
      yellow: "#f3f99d"
      blue: "#57c7ff"
      magenta: "#ff6ac1"
      cyan: "#9aedfe"
      white: "#f1f1f0"
  nord: &nord
    primary:
      background: "#2e3440"
      foreground: "#d8dee9"
      dim_foreground: "#a5abb6"
    cursor:
      text: "#2e3440"
      cursor: "#d8dee9"
    vi_mode_cursor:
      text: "#2e3440"
      cursor: "#d8dee9"
    selection:
      text: CellForeground
      background: "#4c566a"
    search:
      matches:
        foreground: CellBackground
        background: "#88c0d0"
      bar:
        background: "#434c5e"
        foreground: "#d8dee9"
    normal:
      black: "#3b4252"
      red: "#bf616a"
      green: "#a3be8c"
      yellow: "#ebcb8b"
      blue: "#81a1c1"
      magenta: "#b48ead"
      cyan: "#88c0d0"
      white: "#e5e9f0"
    bright:
      black: "#4c566a"
      red: "#bf616a"
      green: "#a3be8c"
      yellow: "#ebcb8b"
      blue: "#81a1c1"
      magenta: "#b48ead"
      cyan: "#8fbcbb"
      white: "#eceff4"
    dim:
      black: "#373e4d"
      red: "#94545d"
      green: "#809575"
      yellow: "#b29e75"
      blue: "#68809a"
      magenta: "#8c738c"
      cyan: "#6d96a5"
      white: "#aeb3bb"

colors: *gruvbox_flat_dark
