#!/usr/bin/env zsh

LANGUAGES_PYTHON_VERSION='3.8.1'
LANGUAGES_GO_VERSION='1.13.6'
LANGUAGES_RUST_VERSION='1.40.0'

export LANGUAGES_PYTHON_VERSION
export LANGUAGES_GO_VERSION
export LANGUAGES_RUST_VERSION
